//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HowYouSay.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HowYouSay.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FullListLabel {
            get {
                return ResourceManager.GetString("FullListLabel", resourceCulture);
            }
        }
        
        internal static string SearchInputPlaceholder {
            get {
                return ResourceManager.GetString("SearchInputPlaceholder", resourceCulture);
            }
        }
        
        internal static string EntryPageTitle {
            get {
                return ResourceManager.GetString("EntryPageTitle", resourceCulture);
            }
        }
        
        internal static string EntryInputPlaceholder {
            get {
                return ResourceManager.GetString("EntryInputPlaceholder", resourceCulture);
            }
        }
        
        internal static string TranslationLabel {
            get {
                return ResourceManager.GetString("TranslationLabel", resourceCulture);
            }
        }
        
        internal static string TranslationInputPlaceholder {
            get {
                return ResourceManager.GetString("TranslationInputPlaceholder", resourceCulture);
            }
        }
        
        internal static string PhoneticLabel {
            get {
                return ResourceManager.GetString("PhoneticLabel", resourceCulture);
            }
        }
        
        internal static string PhoneticInputPlaceholder {
            get {
                return ResourceManager.GetString("PhoneticInputPlaceholder", resourceCulture);
            }
        }
        
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        internal static string LanguageInputPlaceholder {
            get {
                return ResourceManager.GetString("LanguageInputPlaceholder", resourceCulture);
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string NotesInputPlaceholder {
            get {
                return ResourceManager.GetString("NotesInputPlaceholder", resourceCulture);
            }
        }
    }
}
